coverage:
  status:
    project:
      default:
        target: 80%         # 전체 프로젝트 목표 커버리지
        threshold: 1%       # 변화 허용 범위
        informational: true # 실패로 간주하지 않음

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
